export const salesWorkbench = {
  kpis: [
    { tone: 'mint', label: '待执行计划', value: 12, icon: '▤' },
    { tone: 'peach', label: '待跟进报价', value: 9, icon: '📄' },
    { tone: 'mint', label: '待审批合同', value: 6, icon: '✓' },
    { tone: 'sky', label: '待处理订单', value: 18, icon: '🛒' },
    { tone: 'rose', label: '待审核客户', value: 4, icon: '👤' },
    { tone: 'lilac', label: '待出库订单', value: 12, icon: '▦' },
    { tone: 'sand', label: '待处理退货', value: 3, icon: '↩' },
    { tone: 'sky', label: '待回款提醒', value: 11, icon: '⌕' },
    { tone: 'mint', label: '待开票记录', value: 7, icon: '📄' },
    { tone: 'peach', label: '客户拜访计划', value: 5, icon: '👤' },
    { tone: 'rose', label: '逾期未回款', value: 2, icon: '!' },
    { tone: 'lilac', label: '样品跟进', value: 8, icon: '▣' },
    { tone: 'sand', label: '销售预测', value: 14, icon: '▤' },
  ],
  tiles: [
    { label: '客户', sub: '客户管理', count: 238, tint: '#DCE7FB', color: '#5677FC', icon: '👤' },
    { label: '计划', sub: '销售计划', count: 12, tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '报价', sub: '报价管理', count: 46, tint: '#DCE7FB', color: '#5677FC', icon: '📄' },
    { label: '合同', sub: '合同管理', count: 32, tint: '#DCE7FB', color: '#5677FC', icon: '✓' },
    { label: '订单', sub: '订单管理', count: 78, tint: '#DCE7FB', color: '#5677FC', icon: '🛒' },
    { label: '退货', sub: '销售退货', count: 5, tint: '#FBDFDF', color: '#D14D4D', icon: '↩' },
    { label: '换货', sub: '销售换货', count: 2, tint: '#E8DEFB', color: '#8957D8', icon: '⇄' },
    { label: '报表', sub: '销售报表', count: 0, tint: '#DBF3E6', color: '#10B981', icon: '⌕' },
    { label: '回款', sub: '支付记录', count: 19, tint: '#FEF3CD', color: '#B26A24', icon: '¥' },
  ],
  entries: [
    { label: '新增客户', tint: '#DCE7FB', color: '#5677FC', icon: '👤' },
    { label: '制定计划', tint: '#DBF3E6', color: '#10B981', icon: '▤' },
    { label: '新增报价', tint: '#DCE7FB', color: '#5677FC', icon: '📄' },
    { label: '新增合同', tint: '#DCE7FB', color: '#5677FC', icon: '✓' },
    { label: '销售订单', tint: '#DCE7FB', color: '#5677FC', icon: '🛒' },
    { label: '我的审批', tint: '#DCE7FB', color: '#5677FC', icon: '▦' },
  ],
  notices: [
    { type: '重要', text: 'Q2 销售计划执行节奏调整，请各销售经理更新本周跟进记录', time: '2小时前', tone: 'aw-feed-tag-rose' },
    { type: '制度', text: '新版《客户信用额度管理办法》正式发布', time: '1天前', tone: 'aw-feed-tag-sky' },
    { type: '公告', text: '本月重点客户拜访计划已同步至销售中心工作台', time: '3天前', tone: 'aw-feed-tag-peach' },
    { type: '系统', text: '销售订单与仓储出库联动将在本周六凌晨升级', time: '1周前', tone: 'aw-feed-tag-mint' },
    { type: '活动', text: '销售中心月度复盘会议将在周五下午举行', time: '1周前', tone: 'aw-feed-tag-mint' },
  ],
  recent: [
    { title: 'SO-202605-031 销售合同会签', meta: '销售 · 合同管理 · 12分钟前' },
    { title: 'CUS-2026-001 海南星海智能制造有限公司', meta: '销售 · 客户管理 · 1小时前' },
    { title: 'SP-20251221001 荣某定制报价', meta: '销售 · 报价管理 · 今天 09:24' },
    { title: 'PO-202605-022 采购订单复核', meta: '采购 · 采购管理 · 昨天 17:08' },
    { title: 'SO-202605-026 广州智造电子', meta: '销售 · 订单管理 · 昨天 15:30' },
  ],
  focusRows: [
    { code: 'SO-202605-031', customer: '海南星海智能制造有限公司', stage: '合同会签', owner: '老夏', amount: '288,000', status: '审核中' },
    { code: 'QT-202605-018', customer: '深圳荣某精密科技有限公司', stage: '报价跟进', owner: '李文涛', amount: '59,600', status: '待跟进' },
    { code: 'SO-202605-026', customer: '广州智造电子', stage: '待出库', owner: '陈思源', amount: '126,800', status: '待处理' },
  ],
};
